### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/ItemScene#3]
* [ ] Child objects and sub-trees (include of ability to create groups of elements)
* [ ] Implement Z-Order
* [ ] Implement hand-dragging
* [ ] Smooth Scrolling **[Optionally]**
* [ ] Apply zoom factor to scrolling speed (but, re-align camera on zoom change to avoid a broken alignment)
* [ ] Implement the "animated items" render scheme where visible surface will be updated often.
* [x] <s>Replace `QList` container with [PtrList](https://github.com/WohlSoft/PtrList) to guarantee same pointer address in the memory.</s> Instead of this, `QSet` was used inside of tree to hold dynamically allocated items.
* [ ] Allow polymorphism for `PGE_EditSceneItem` to allow different item types.
* [ ] Implement collision check callback called on move or mouse release by optional choose
* [ ] Implement background and foreground render callbacks (to fill empty surface with something or draw the grid or any overground meta-signs or animations)
